# #####################################
# #
# #     ClanPlugin by CodingAir
# #
# #####################################
# # Prefix- & Suffix-Variables:
# # - %clan_color% := The Clan-Rank-Color
# # - %clanname% := The name of the clan
# # - %clan_rank% := The rank of the clan
# #####################################
# # Chat-Format-Variables:
# # - %clan_color% := The Clan-Rank-Color
# # - %clanname% := The name of the clan
# # - %clan_rank% := The rank of the clan
# # - %name% := The name of the name
# # - %message% := The message of the input
# #####################################
Clans:
  BungeeCord: false
  Synchronization:
    Server:
      Port: 3006
  Economy:
    Enabled: true
    Taxes:
      Enabled: true
      Taxes_Per_Member: 100
      Days: 1
  Player:
    Prefix_Suffix:
      Enabled: true
      With_Clan:
        Prefix: "%clan_color%%clanname% &8| &7"
        Suffix: ""
      Without_Clan:
        Prefix: "&7"
        Suffix: ""
    Globalchat:
      Enabled: true
      OnlyPrefix:
        Enabled: true
        Prefix:
          With_Clan: "%clan_color%%clanname% &8~ &7"
          Without_Clan: "&7"
      Format_With_Clan: "%clan_color%%clanname% &8~ &7%name% &8> &7%message%"
      Format_Without_Clan: "&7%name% &8> &7%message%"
  Clan:
    Bases: true
    Rank_Colors:
      Leader: "&c"
      Trusted: "&b"
      Member: "&7"
    Max_Name_Length: 4
    PrivateChat:
      Format: "%clan_color%%clanname% &8| %rank_color%%name% &8> &7%message%"
  Teleport:
    Allow_Move: false
    Teleport_Time: 5
  Permissions:
    Trusted:
      Kick: true
      Invite: true
      Alliance: false
      Neutral: false
      ToggleChat: true
      Promote: false
      Demote: false
      Set_Base: true
      Set_Icon: true
      Withdraw: false
  TopClans:
    Colors:
      1: "&4"
      2: "&c"
      3: "&a"
      4: "&b"
      5: "&e"
      Default: "&7"