name: ClanSystem
author: CodingAir
version: 1.1.5
description: ClanSystem
main: de.CodingAir.ClanSystem.ClanSystem
softdepend: [PlaceholderAPI]

commands:
  Clan:
    description: CMD of ClanSystem
    aliases: [clans, c]
  Options:
    description: CMD of ClanSystem