name: ClanSystem
author: CodingAir
version: 1.1.3
description: ClanSystem
main: de.CodingAir.ClanSystem.ClanSystem

commands:
  Clan:
    description: CMD of ClanSystem
    aliases: [clans, c]
  Options:
    description: CMD of ClanSystem